import Head from 'next/head'
import PageWrapper from '@components/PageWrapper';

export default function Home() {
  return (
    <PageWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello</h1>
    </PageWrapper>
  )
}
